version: '3.7'
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  multi-scrobbler:
    # Uncomment if you want to override the service's Dockerfile to one in the .devcontainer 
    # folder. Note that the path of the Dockerfile and context is relative to the *primary* 
    # docker-compose.yml file (the first in the devcontainer.json "dockerComposeFile"
    # array). The sample below assumes your primary file is in the root of your project.
    #
    # build:
    #   context: .
    #   dockerfile: .devcontainer/Dockerfile

    image: mcr.microsoft.com/devcontainers/javascript-node:1-20-bookworm

    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspaces:cached
    command: sleep infinity

  valkey:
    image: valkey/valkey
    env_file:
      - path: ./.env
        required: false